### ISSUE TITLE
Unclear I've bought 1 or 10 or more items

### ISSUE THREAD

**Issue by DizzyEggAlleg** [aaronbolyard/itsyscape#7]
I think it should be more clear when using the 1, 10, 100 buttons when buying items - my first time I filled up my inventory, because I was expecting 1, 10 or 100 to appear in the text entry box, and the press buy - it wasn't clear that I was buying the items just by pressing the 1, 10, 100 buttons!! I think pressing one of these should add that number to the text box, or open a box saying "buy 10 x?".

**Comment by aaronbolyard** [comment]
That makes perfect sense. Will do.

**Comment by aaronbolyard** [comment]
Fixed.
